# Generated by Django 3.0.4 on 2020-03-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakanyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroute',
            old_name='route',
            new_name='name',
        ),
    ]
