# Generated by Django 3.0.3 on 2020-03-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakanyapp', '0003_auto_20200323_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestep',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
